### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by phamxtien** [snowby666/poe-api-wrapper#127] opened 2024-03-21 09:53 UTC
Today it return error
=====================
An unknown error occurred. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}

**Comment by PMajesty** [comment] 2024-03-21 14:33
I think this happens when you specify a chat. I have the same issue, I worked around it by not specifying a chat for now

**Comment by phamxtien** [comment] 2024-03-21 22:23
It return error on second prompt
First prompt: Hi >> It's OK
Second prompt: How are you today >> It returns error
But on poe.com it's OK :((
![image](https://github.com/snowby666/poe-api-wrapper/assets/33739597/7499cdd1-3f8e-4109-9329-608a25b11b80)

**Comment by phamxtien** [comment] 2024-03-21 23:48
It error on this line
![image](https://github.com/snowby666/poe-api-wrapper/assets/33739597/325431f8-81c6-4238-8c79-4601d9c824e8)

**Comment by phamxtien** [comment] 2024-03-22 04:18
> I think this happens when you specify a chat. I have the same issue, I worked around it by not specifying a chat for now

I followed these instructions and options 1, 2, and 3 all returned errors at the second prompt

![image](https://github.com/snowby666/poe-api-wrapper/assets/33739597/83772768-d820-4c81-abe1-29c20609823d)

**Comment by PMajesty** [comment] 2024-03-22 04:51
> > I think this happens when you specify a chat. I have the same issue, I worked around it by not specifying a chat for now
> 
> I followed these instructions and options 1, 2, and 3 all returned errors at the second prompt
> 
> ![image](https://private-user-images.githubusercontent.com/33739597/315883676-83772768-d820-4c81-abe1-29c20609823d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODMzMDgsIm5iZiI6MTcxMTA4MzAwOCwicGF0aCI6Ii8zMzczOTU5Ny8zMTU4ODM2NzYtODM3NzI3NjgtZDgyMC00YzgxLWFiZTEtMjljMjA2MDk4MjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0NTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YTRhOGEzN2YyNGJhY2QxMTdlMDFmNTk4NjU4MzZmNDYyMDVhMDc2OTljMjZmNTFkOTg0NGVjNjQ1OTg0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztzyXmgWlIUL7UWkSnCmBKsd9rnM-vYYeYPEBsIq8VQ)

I mean, for the time being, until the bug is fixed, I do just `send_message(bot, message)`. No chatId, no chatCode, no reference to any chat at all. Yes you can only send 1 message in such a way, but at least it works.

But it is a bug. I have that too

**Comment by snowby666** [comment] 2024-03-22 10:00
This was caused by a indent mistake. I'll fix it in the next update with other features.

**Comment by snowby666** [comment] 2024-03-22 15:56
this is fixed in the new version

**Closed by snowby666** 2024-03-22 15:56 UTC

**Comment by PMajesty** [comment] 2024-03-23 12:40
@snowby666 thank you for your efforts. Great package BTW!!!

**Comment by FightingFranky** [comment] 2024-06-12 18:50
> this is fixed in the new version

I don't think this is solved, it happened to me a lot.

  File "/Users/edy/miniconda3/lib/python3.11/site-packages/poe_api_wrapper/api.py", line 748, in send_message
    raise e
  File "/Users/edy/miniconda3/lib/python3.11/site-packages/poe_api_wrapper/api.py", line 733, in send_message
    raise RuntimeError(f"An unknown error occurred. Raw response data: {message_data}")
RuntimeError: An unknown error occurred. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}
