### ISSUE TITLE
question about sent_message()

### ISSUE THREAD

**Issue by llllly26** [snowby666/poe-api-wrapper#34] opened 2023-09-12 04:59 UTC
Hi, i get the token through your step, and when i run the code, `print(client.get_chat_history())` can return, but when i run the part about `for chunk in client.send_message(bot, message):`,  there is nothing returned. then i debug the code, and i find that there is a problem about `self.connect_ws()` in `api.py`. in api.py-`line223`, `self.ws_connected` was `false`, so the program stucks in an infinite loop. But the other one that use my token can correctly run the code, i don't know what is wrong of me.

**Comment by snowby666** [comment] 2023-09-13 17:25
I will update the api soon

**Comment by snowby666** [comment] 2023-09-14 14:30
Can you check if this error still occur with the new version?

**Comment by wacharlin** [comment] 2023-09-15 04:24
> Can you check if this error still occur with the new version?
Hi, i still can not run sucessfully. This time, i even can not run the code `print(client.get_chat_history())`. the new error is in `api.py`, `line 256`, in `connect_ws` that: 
![image](https://github.com/snowby666/poe-api-wrapper/assets/38215077/767ed560-d440-4d79-bcc3-baf6d3aae74b)
so, i can't verify the `send_message()` either.  
This time i also can not successfully connect.What's wrong? Thank you!

**Comment by wacharlin** [comment] 2023-09-15 04:29
> Can you check if this error still occur with the new version?

could you please show me the version of python dependency package?

**Comment by snowby666** [comment] 2023-09-15 05:06
Can you check if you re using vpn or proxy while running this code? And It would be better if you can specify your OS and python version.

**Comment by snowby666** [comment] 2023-09-15 10:42
I think there might be a problem with your SSL/TLS setup. If possible can you fork this repo, adjust this line and test on your local machine:
line 169 : 
`self.channel_url = f'wss://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'`

to this one:

` self.channel_url = f'ws://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'`

**Comment by wacharlin** [comment] 2023-09-15 11:10
> Can you check if you re using vpn or proxy while running this code? And It would be better if you can specify your OS and python version.

my OS is win10,and my python version is 3.10.12

**Comment by wacharlin** [comment] 2023-09-15 11:20
> I think there might be a problem with your SSL/TLS setup. If possible can you fork this repo, adjust this line and test on your local machine: line 169 :
> 
> ```python
> self.channel_url = f'wss://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'
> ```
> 
> to this one:
> 
> ```python
> self.channel_url = f'ws://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'
> ```
the question is still remaining.

**Comment by wacharlin** [comment] 2023-09-15 12:05
> I think there might be a problem with your SSL/TLS setup. If possible can you fork this repo, adjust this line and test on your local machine: line 169 :
> 
> ```python
> self.channel_url = f'wss://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'
> ```
> 
> to this one:
> 
> ```python
> self.channel_url = f'ws://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'
> ```

if the problem is from the port?  in my win10, http(s) port is: 4780; socks port is 4781. whether your code use port anywhere?
![image](https://github.com/snowby666/poe-api-wrapper/assets/38215077/da8ce39c-5ef3-4e4a-a4bc-f9d12557bce7)

**Comment by snowby666** [comment] 2023-09-16 06:35
can you check this for me?
https://poe.com/api/settings

**Comment by wacharlin** [comment] 2023-09-16 11:03
> https://poe.com/api/settings

{"tchannelData":{"minSeq":"8130883414","channel":"poe-chan60-8888-mkhevzuqednzwejckppj","channelHash":"15169644638001127031","boxName":"chan60-8888","baseHost":"poe.com","targetUrl":"","enableWebsocket":true}}

**Comment by snowby666** [comment] 2023-09-16 16:59
> > I think there might be a problem with your SSL/TLS setup. If possible can you fork this repo, adjust this line and test on your local machine: line 169 :
> > ```python
> > self.channel_url = f'wss://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to this one:
> > ```python
> > self.channel_url = f'ws://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'
> > ```
> 
> if the problem is from the port? in my win10, http(s) port is: 4780; socks port is 4781. whether your code use port anywhere? ![image](https://user-images.githubusercontent.com/38215077/268274062-da8ce39c-5ef3-4e4a-a4bc-f9d12557bce7.png)

No, the lib doesn't use port. How about setting up a virtual environment to test it first. This time try using requests or httpx lib then send a request to a url to check if it works

**Comment by wacharlin** [comment] 2023-09-17 01:23
> > > I think there might be a problem with your SSL/TLS setup. If possible can you fork this repo, adjust this line and test on your local machine: line 169 :
> > > ```python
> > > self.channel_url = f'wss://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to this one:
> > > ```python
> > > self.channel_url = f'ws://{self.ws_domain}.tch.{self.tchannel_data["baseHost"]}/up/{self.tchannel_data["boxName"]}/updates?min_seq={self.tchannel_data["minSeq"]}&channel={self.tchannel_data["channel"]}&hash={self.tchannel_data["channelHash"]}'
> > > ```
> > 
> > 
> > if the problem is from the port? in my win10, http(s) port is: 4780; socks port is 4781. whether your code use port anywhere? ![image](https://user-images.githubusercontent.com/38215077/268274062-da8ce39c-5ef3-4e4a-a4bc-f9d12557bce7.png)
> 
> No, the lib doesn't use port. How about setting up a virtual environment to test it first. This time try using requests or httpx lib then send a request to a url to check if it works

hi, how to test it?

**Comment by snowby666** [comment] 2023-09-17 02:27
First create a venv in your folder:
```sh 
python -m venv .venv
.venv\Scripts\activate.bat      
```

Then create a test.py
```py
import requests
import httpx

url = 'http://example.com'

try:
    response = requests.get(url)
    if response.status_code == 200:
        print("Connection successful. Ping to example.com using requests was sent.")
    else:
        print("Connection failed. Unable to ping example.com using requests.")
except requests.exceptions.RequestException as e:
    print("Connection failed. Exception:", e)
    
    
try:
    with httpx.Client() as client:
        response = client.get(url)
        if response.status_code == 200:
            print("Connection successful. Ping to example.com using httpx was sent.")
        else:
            print("Connection failed. Unable to ping example.com using httpx.")
except httpx.RequestError as e:
    print("Connection failed. Exception:", e)
 ```
 Run test.py
 ```sh
 python test.py
 ```

**Comment by wacharlin** [comment] 2023-09-17 06:40
> First create a venv in your folder:
> 
> ```shell
> python -m venv .venv
> .venv\Scripts\activate.bat      
> ```
> 
> Then create a test.py
> 
> ```python
> import requests
> import httpx
> 
> url = 'http://example.com'
> 
> try:
>     response = requests.get(url)
>     if response.status_code == 200:
>         print("Connection successful. Ping to example.com using requests was sent.")
>     else:
>         print("Connection failed. Unable to ping example.com using requests.")
> except requests.exceptions.RequestException as e:
>     print("Connection failed. Exception:", e)
>     
>     
> try:
>     with httpx.Client() as client:
>         response = client.get(url)
>         if response.status_code == 200:
>             print("Connection successful. Ping to example.com using httpx was sent.")
>         else:
>             print("Connection failed. Unable to ping example.com using httpx.")
> except httpx.RequestError as e:
>     print("Connection failed. Exception:", e)
> ```
> 
> Run test.py
> 
> ```shell
> python test.py
> ```

hi, it can work.
![image](https://github.com/snowby666/poe-api-wrapper/assets/38215077/d598cad4-5491-45b5-a825-9ec5765a66df)

**Comment by snowby666** [comment] 2023-09-17 07:31
Alright it seems like the issues didnt come from the httpx lib, how about the websocket-client lib then. Can you do 1 more test for me (in venv as well)
```py
import websocket

def on_open(ws):
    print("WebSocket connection established")
    ws.send("Hello, server!")

def on_message(ws, message):
    print("Received message from server:", message)

def on_close(ws, close_status_code, close_msg):
    print("Websocket connection closed with status code:", close_status_code, "and message:", close_msg)

def on_error(ws, error):
    print("WebSocket error:", error)

url = "wss://javascript.info/article/websocket/demo/hello"

ws = websocket.WebSocketApp(url,
                            on_open=on_open,
                            on_message=on_message,
                            on_close=on_close,
                            on_error=on_error)
ws.run_forever()
```

**Comment by wacharlin** [comment] 2023-09-17 07:54
> ```python
> import websocket
> 
> def on_open(ws):
>     print("WebSocket connection established")
>     ws.send("Hello, server!")
> 
> def on_message(ws, message):
>     print("Received message from server:", message)
> 
> def on_close(ws, close_status_code, close_msg):
>     print("Websocket connection closed with status code:", close_status_code, "and message:", close_msg)
> 
> def on_error(ws, error):
>     print("WebSocket error:", error)
> 
> url = "wss://javascript.info/article/websocket/demo/hello"
> 
> ws = websocket.WebSocketApp(url,
>                             on_open=on_open,
>                             on_message=on_message,
>                             on_close=on_close,
>                             on_error=on_error)
> ws.run_forever()
> ```

that's ok.
![image](https://github.com/snowby666/poe-api-wrapper/assets/38215077/6458c270-9598-4787-b148-b06b4a1af258)

**Comment by snowby666** [comment] 2023-09-17 08:01
can you try this again in your venv?
```py
for chunk in client.send_message(bot, message):,
     print(chunk['response'], end='', flush=True)
```

**Comment by wacharlin** [comment] 2023-09-17 11:07
> ```python
> for chunk in client.send_message(bot, message):,
>      print(chunk['response'], end='', flush=True)
> ```

I'm sorry, that it still has the same problems. 
![image](https://github.com/snowby666/poe-api-wrapper/assets/38215077/601608d9-e6ff-4251-91a5-4ef7a9e7f5c7)
code is:
`client = PoeApi(token)
print(client.get_chat_history())

bot = "chinchilla"
message = "What is reverse engineering?"
#
output = ""
for chunk in client.send_message(bot, message):
    print('hello')
    output += chunk["response"]
print(output)`

**Comment by snowby666** [comment] 2023-09-17 11:38
Can you check your quora token if its valid?
You must also login poe.com with the same account on quora

**Comment by wacharlin** [comment] 2023-09-17 12:45
> Can you check your quora token if its valid? You must also login poe.com with the same account on quora

yes, my token that can run successully because i give it to the other one, and he can run successful, but i can't. --

**Comment by wacharlin** [comment] 2023-09-18 14:51
> > > ```python
> > > import websocket
> > > 
> > > def on_open(ws):
> > >     print("WebSocket connection established")
> > >     ws.send("Hello, server!")
> > > 
> > > def on_message(ws, message):
> > >     print("Received message from server:", message)
> > > 
> > > def on_close(ws, close_status_code, close_msg):
> > >     print("Websocket connection closed with status code:", close_status_code, "and message:", close_msg)
> > > 
> > > def on_error(ws, error):
> > >     print("WebSocket error:", error)
> > > 
> > > url = "wss://javascript.info/article/websocket/demo/hello"
> > > 
> > > ws = websocket.WebSocketApp(url,
> > >                             on_open=on_open,
> > >                             on_message=on_message,
> > >                             on_close=on_close,
> > >                             on_error=on_error)
> > > ws.run_forever()
> > > ```
> > 
> > 
> > that's ok. ![image](https://user-images.githubusercontent.com/38215077/268489760-6458c270-9598-4787-b148-b06b4a1af258.png)
> 
> How long did it take you to connect to the ws with this code? Maybe the timeout in the api is too short.

about 5s.

**Comment by wacharlin** [comment] 2023-09-19 07:31
> Alright it seems like the issues didnt come from the httpx lib, how about the websocket-client lib then. Can you do 1 more test for me (in venv as well)
> 
> ```python
> import websocket
> 
> def on_open(ws):
>     print("WebSocket connection established")
>     ws.send("Hello, server!")
> 
> def on_message(ws, message):
>     print("Received message from server:", message)
> 
> def on_close(ws, close_status_code, close_msg):
>     print("Websocket connection closed with status code:", close_status_code, "and message:", close_msg)
> 
> def on_error(ws, error):
>     print("WebSocket error:", error)
> 
> url = "wss://javascript.info/article/websocket/demo/hello"
> 
> ws = websocket.WebSocketApp(url,
>                             on_open=on_open,
>                             on_message=on_message,
>                             on_close=on_close,
>                             on_error=on_error)
> ws.run_forever()
> ```

hi, i am trying this test, and find that it is error this time.
![image](https://github.com/snowby666/poe-api-wrapper/assets/38215077/d658b4c6-2aa9-46a1-bec8-c1494da43206)

**Comment by wacharlin** [comment] 2023-09-19 07:39
> Can you check if you re using vpn or proxy while running this code? And It would be better if you can specify your OS and python version.

i am using vpn now.

**Comment by wacharlin** [comment] 2023-09-23 15:52
what is the specifical proxy?  how to use the proxy?

**Comment by snowby666** [comment] 2024-06-21 07:17
This is be fixed in v.1.5.4

**Closed by snowby666** 2024-06-21 07:17 UTC
Labels: Clash (3rd party proxy clients)
